[package]
name = "bempline"
version = "0.2.0"
description = "Simple template library"
authors = ["genuinebyte <crates@genbyte.dev>"]
repository = "https://git.sr.ht/~genbyte/bempline"
readme = "README.md"
keywords = ["template", "html"]
categories = ["template-engine"]
license = "ISC"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
